services:
  db:
    image: postgres:latest
    hostname: localhost
    ports:
      - "80:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
